/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 v1.glb 
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function V1(props) {
  const { nodes, materials } = useGLTF('/models/credenz24/v1/v1.glb')
  return (
    <group {...props} dispose={null} scale={0.15}>
      <group position={[-183.294, 6.154, 9.687]} scale={1.146}>
        <mesh geometry={nodes.group1109515510.geometry} material={materials['mat14.001']} rotation={[Math.PI / 2, 0, 0]} scale={34.387} />
        <mesh geometry={nodes.group1109883496.geometry} material={materials.mat17} rotation={[Math.PI / 2, 0, 0]} scale={34.387} />
        <mesh geometry={nodes.group1125255076.geometry} material={materials['mat14.001']} rotation={[Math.PI / 2, 0, 0]} scale={34.387} />
        <mesh geometry={nodes.group1130434813.geometry} material={materials.mat15} rotation={[Math.PI / 2, 0, 0]} scale={34.387} />
        <mesh geometry={nodes.group1204232670.geometry} material={materials.mat17} rotation={[Math.PI / 2, 0, 0]} scale={34.387} />
        <mesh geometry={nodes.group122146175.geometry} material={materials.mat8} rotation={[Math.PI / 2, 0, 0]} scale={34.387} />
        <mesh geometry={nodes.group1224037610.geometry} material={materials['mat14.001']} rotation={[Math.PI / 2, 0, 0]} scale={34.387} />
        <group rotation={[Math.PI / 2, 0, 0]} scale={34.387}>
          <mesh geometry={nodes.group1248881623_1.geometry} material={materials.mat16} />
          <mesh geometry={nodes.group1248881623_2.geometry} material={materials.mat8} />
        </group>
        <mesh geometry={nodes.group1249644479.geometry} material={materials.mat17} rotation={[Math.PI / 2, 0, 0]} scale={34.387} />
        <mesh geometry={nodes.group1319652846.geometry} material={materials['mat14.001']} rotation={[Math.PI / 2, 0, 0]} scale={34.387} />
        <mesh geometry={nodes.group1331663071.geometry} material={materials.mat12} rotation={[Math.PI / 2, 0, 0]} scale={34.387} />
        <mesh geometry={nodes.group1333689153.geometry} material={materials['mat21.001']} rotation={[Math.PI / 2, 0, 0]} scale={34.387} />
        <mesh geometry={nodes.group1340366337.geometry} material={materials['mat14.001']} rotation={[Math.PI / 2, 0, 0]} scale={34.387} />
        <mesh geometry={nodes.group1357515875.geometry} material={materials.mat5} rotation={[Math.PI / 2, 0, 0]} scale={34.387} />
        <mesh geometry={nodes.group1380036288.geometry} material={materials.mat15} rotation={[Math.PI / 2, 0, 0]} scale={34.387} />
        <mesh geometry={nodes.group1429872227.geometry} material={materials['mat21.001']} rotation={[Math.PI / 2, 0, 0]} scale={34.387} />
        <mesh geometry={nodes.group1441484207.geometry} material={materials.mat8} rotation={[Math.PI / 2, 0, 0]} scale={34.387} />
        <mesh geometry={nodes.group1465148937.geometry} material={materials.mat8} rotation={[Math.PI / 2, 0, 0]} scale={34.387} />
        <mesh geometry={nodes.group1476506327.geometry} material={materials.mat17} rotation={[Math.PI / 2, 0, 0]} scale={34.387} />
        <mesh geometry={nodes.group1490881220.geometry} material={materials['mat21.001']} rotation={[Math.PI / 2, 0, 0]} scale={34.387} />
        <mesh geometry={nodes.group1499757032.geometry} material={materials.mat8} rotation={[Math.PI / 2, 0, 0]} scale={34.387} />
        <mesh geometry={nodes.group1502905482.geometry} material={materials.mat17} rotation={[Math.PI / 2, 0, 0]} scale={34.387} />
        <mesh geometry={nodes.group1526770630.geometry} material={materials.mat5} rotation={[Math.PI / 2, 0, 0]} scale={34.387} />
        <mesh geometry={nodes.group1552610862.geometry} material={materials.mat8} rotation={[Math.PI / 2, 0, 0]} scale={34.387} />
        <mesh geometry={nodes.group1609899504.geometry} material={materials['mat14.001']} rotation={[Math.PI / 2, 0, 0]} scale={34.387} />
        <mesh geometry={nodes.group1611104514.geometry} material={materials.mat8} rotation={[Math.PI / 2, 0, 0]} scale={34.387} />
        <group rotation={[Math.PI / 2, 0, 0]} scale={34.387}>
          <mesh geometry={nodes.group1639735897_1.geometry} material={materials.mat15} />
          <mesh geometry={nodes.group1639735897_2.geometry} material={materials.mat8} />
          <mesh geometry={nodes.group1639735897_3.geometry} material={materials.mat16} />
        </group>
        <mesh geometry={nodes.group1650019230.geometry} material={materials.mat17} rotation={[Math.PI / 2, 0, 0]} scale={34.387} />
        <mesh geometry={nodes.group1659503815.geometry} material={materials['mat14.001']} rotation={[Math.PI / 2, 0, 0]} scale={34.387} />
        <mesh geometry={nodes.group1686683300.geometry} material={materials.mat15} rotation={[Math.PI / 2, 0, 0]} scale={34.387} />
        <mesh geometry={nodes.group1691778719.geometry} material={materials.mat5} rotation={[Math.PI / 2, 0, 0]} scale={34.387} />
        <mesh geometry={nodes.group1697237491.geometry} material={materials.mat5} rotation={[Math.PI / 2, 0, 0]} scale={34.387} />
        <mesh geometry={nodes.group1701587960.geometry} material={materials.mat12} rotation={[Math.PI / 2, 0, 0]} scale={34.387} />
        <mesh geometry={nodes.group1703920967.geometry} material={materials.mat16} rotation={[Math.PI / 2, 0, 0]} scale={34.387} />
        <mesh geometry={nodes.group1723449364.geometry} material={materials.mat12} rotation={[Math.PI / 2, 0, 0]} scale={34.387} />
        <mesh geometry={nodes.group1728621429.geometry} material={materials.mat17} rotation={[Math.PI / 2, 0, 0]} scale={34.387} />
        <mesh geometry={nodes.group1751252301.geometry} material={materials.mat10} rotation={[Math.PI / 2, 0, 0]} scale={34.387} />
        <mesh geometry={nodes.group1854070983.geometry} material={materials.mat5} rotation={[Math.PI / 2, 0, 0]} scale={34.387} />
        <mesh geometry={nodes.group1881423126.geometry} material={materials.mat12} rotation={[Math.PI / 2, 0, 0]} scale={34.387} />
        <mesh geometry={nodes.group1891745208.geometry} material={materials.mat5} rotation={[Math.PI / 2, 0, 0]} scale={34.387} />
        <mesh geometry={nodes.group1936563596.geometry} material={materials.mat5} rotation={[Math.PI / 2, 0, 0]} scale={34.387} />
        <mesh geometry={nodes.group1984813714.geometry} material={materials.mat15} rotation={[Math.PI / 2, 0, 0]} scale={34.387} />
        <mesh geometry={nodes.group1991484969.geometry} material={materials.mat17} rotation={[Math.PI / 2, 0, 0]} scale={34.387} />
        <mesh geometry={nodes.group1998152179.geometry} material={materials.mat12} rotation={[Math.PI / 2, 0, 0]} scale={34.387} />
        <mesh geometry={nodes.group2015766892.geometry} material={materials.mat16} rotation={[Math.PI / 2, 0, 0]} scale={34.387} />
        <group rotation={[Math.PI / 2, 0, 0]} scale={34.387}>
          <mesh geometry={nodes.group2024440113_1.geometry} material={materials['mat14.001']} />
          <mesh geometry={nodes.group2024440113_2.geometry} material={materials.mat17} />
          <mesh geometry={nodes.group2024440113_3.geometry} material={materials.mat15} />
        </group>
        <mesh geometry={nodes.group2032867843.geometry} material={materials['mat21.001']} rotation={[Math.PI / 2, 0, 0]} scale={34.387} />
        <mesh geometry={nodes.group2103999571.geometry} material={materials.mat12} rotation={[Math.PI / 2, 0, 0]} scale={34.387} />
        <mesh geometry={nodes.group2115609096.geometry} material={materials.mat16} rotation={[Math.PI / 2, 0, 0]} scale={34.387} />
        <mesh geometry={nodes.group2123421558.geometry} material={materials.mat17} rotation={[Math.PI / 2, 0, 0]} scale={34.387} />
        <mesh geometry={nodes.group2130245980.geometry} material={materials.mat16} rotation={[Math.PI / 2, 0, 0]} scale={34.387} />
        <mesh geometry={nodes.group2133724846.geometry} material={materials['mat21.001']} rotation={[Math.PI / 2, 0, 0]} scale={34.387} />
        <mesh geometry={nodes.group254883405.geometry} material={materials.mat16} rotation={[Math.PI / 2, 0, 0]} scale={34.387} />
        <mesh geometry={nodes.group293567500.geometry} material={materials['mat14.001']} rotation={[Math.PI / 2, 0, 0]} scale={34.387} />
        <mesh geometry={nodes.group295412224.geometry} material={materials.mat17} rotation={[Math.PI / 2, 0, 0]} scale={34.387} />
        <mesh geometry={nodes.group316248503.geometry} material={materials.mat12} rotation={[Math.PI / 2, 0, 0]} scale={34.387} />
        <mesh geometry={nodes.group402951083.geometry} material={materials['mat21.001']} rotation={[Math.PI / 2, 0, 0]} scale={34.387} />
        <mesh geometry={nodes.group410031999.geometry} material={materials['mat14.001']} rotation={[Math.PI / 2, 0, 0]} scale={34.387} />
        <mesh geometry={nodes.group410845292.geometry} material={materials.mat15} rotation={[Math.PI / 2, 0, 0]} scale={34.387} />
        <mesh geometry={nodes.group420469477.geometry} material={materials.mat17} rotation={[Math.PI / 2, 0, 0]} scale={34.387} />
        <mesh geometry={nodes.group425647546.geometry} material={materials['mat14.001']} rotation={[Math.PI / 2, 0, 0]} scale={34.387} />
        <mesh geometry={nodes.group445682376.geometry} material={materials.mat17} rotation={[Math.PI / 2, 0, 0]} scale={34.387} />
        <mesh geometry={nodes.group487546049.geometry} material={materials['mat21.001']} rotation={[Math.PI / 2, 0, 0]} scale={34.387} />
        <mesh geometry={nodes.group542659570.geometry} material={materials.mat15} rotation={[Math.PI / 2, 0, 0]} scale={34.387} />
        <mesh geometry={nodes.group550546789.geometry} material={materials.mat5} rotation={[Math.PI / 2, 0, 0]} scale={34.387} />
        <group rotation={[Math.PI / 2, 0, 0]} scale={34.387}>
          <mesh geometry={nodes.group582159379_1.geometry} material={materials['mat14.001']} />
          <mesh geometry={nodes.group582159379_2.geometry} material={materials['mat21.001']} />
        </group>
        <mesh geometry={nodes.group615460451.geometry} material={materials.mat15} rotation={[Math.PI / 2, 0, 0]} scale={34.387} />
        <mesh geometry={nodes.group620926883.geometry} material={materials['mat21.001']} rotation={[Math.PI / 2, 0, 0]} scale={34.387} />
        <mesh geometry={nodes.group637847627.geometry} material={materials.mat17} rotation={[Math.PI / 2, 0, 0]} scale={34.387} />
        <mesh geometry={nodes.group645035792.geometry} material={materials.mat17} rotation={[Math.PI / 2, 0, 0]} scale={34.387} />
        <mesh geometry={nodes.group645928749.geometry} material={materials.mat5} rotation={[Math.PI / 2, 0, 0]} scale={34.387} />
        <mesh geometry={nodes.group648967498.geometry} material={materials.mat17} rotation={[Math.PI / 2, 0, 0]} scale={34.387} />
        <mesh geometry={nodes.group652122083.geometry} material={materials.mat8} rotation={[Math.PI / 2, 0, 0]} scale={34.387} />
        <mesh geometry={nodes.group682183177.geometry} material={materials['mat21.001']} rotation={[Math.PI / 2, 0, 0]} scale={34.387} />
        <mesh geometry={nodes.group68280000.geometry} material={materials.mat17} rotation={[Math.PI / 2, 0, 0]} scale={34.387} />
        <mesh geometry={nodes.group708609790.geometry} material={materials['mat21.001']} rotation={[Math.PI / 2, 0, 0]} scale={34.387} />
        <mesh geometry={nodes.group716875044.geometry} material={materials.mat12} rotation={[Math.PI / 2, 0, 0]} scale={34.387} />
        <mesh geometry={nodes.group719063850.geometry} material={materials.mat5} rotation={[Math.PI / 2, 0, 0]} scale={34.387} />
        <mesh geometry={nodes.group730979645.geometry} material={materials.mat17} rotation={[Math.PI / 2, 0, 0]} scale={34.387} />
        <mesh geometry={nodes.group743730337.geometry} material={materials['mat21.001']} rotation={[Math.PI / 2, 0, 0]} scale={34.387} />
        <mesh geometry={nodes.group774917317.geometry} material={materials.mat5} rotation={[Math.PI / 2, 0, 0]} scale={34.387} />
        <mesh geometry={nodes.group8081122.geometry} material={materials.mat17} rotation={[Math.PI / 2, 0, 0]} scale={34.387} />
        <mesh geometry={nodes.group828060803.geometry} material={materials.mat8} rotation={[Math.PI / 2, 0, 0]} scale={34.387} />
        <mesh geometry={nodes.group868781494.geometry} material={materials.mat12} rotation={[Math.PI / 2, 0, 0]} scale={34.387} />
        <mesh geometry={nodes.group874545954.geometry} material={materials.mat8} rotation={[Math.PI / 2, 0, 0]} scale={34.387} />
        <mesh geometry={nodes.group948092280.geometry} material={materials['mat21.001']} rotation={[Math.PI / 2, 0, 0]} scale={34.387} />
        <mesh geometry={nodes.group95801961.geometry} material={materials.mat5} rotation={[Math.PI / 2, 0, 0]} scale={34.387} />
        <mesh geometry={nodes.group989006632.geometry} material={materials.mat12} rotation={[Math.PI / 2, 0, 0]} scale={34.387} />
      </group>
      <group position={[0.318, 4.964, -1.013]} scale={[7.388, 1, 7.388]}>
        <mesh geometry={nodes.Cylinder004.geometry} material={materials.RockBase} />
        <mesh geometry={nodes.Cylinder004_1.geometry} material={materials.walls} />
        <mesh geometry={nodes.Cylinder004_2.geometry} material={materials.Roof} />
        <mesh geometry={nodes.Cylinder004_3.geometry} material={materials['Window Cover']} />
        <mesh geometry={nodes.Cylinder004_4.geometry} material={materials['Material.002']} />
        <mesh geometry={nodes.Cylinder004_5.geometry} material={materials.WallAccents} />
        <mesh geometry={nodes.Cylinder004_6.geometry} material={materials.Sand} />
        <mesh geometry={nodes.Cylinder004_7.geometry} material={materials.subMetal} />
        <mesh geometry={nodes.Cylinder004_8.geometry} material={materials.Material} />
        <mesh geometry={nodes.Cylinder004_9.geometry} material={materials.Light} />
      </group>
      <mesh geometry={nodes.Cube001.geometry} material={materials['Dock.001']} position={[17.504, 3.673, -9.558]} rotation={[0, 0.646, 0]} scale={[0.321, 1, 1.72]} />
      <group position={[25.443, 0.886, -3.593]} scale={[2.771, 0.23, 0.727]}>
        <mesh geometry={nodes.Cube004.geometry} material={materials.Dock} />
        <mesh geometry={nodes.Cube004_1.geometry} material={materials['Dock.001']} />
      </group>
      <group position={[26.669, 0.886, -17.874]} rotation={[0, Math.PI / 2, 0]} scale={[2.771, 0.23, 0.727]}>
        <mesh geometry={nodes.Cube005.geometry} material={materials.Dock} />
        <mesh geometry={nodes.Cube005_1.geometry} material={materials['Dock.001']} />
      </group>
      <mesh geometry={nodes.Railing.geometry} material={materials.FencePost} position={[-3.081, 26.538, -1.109]} scale={[0.956, 1, 0.956]} />
      <mesh geometry={nodes.Cube.geometry} material={nodes.Cube.material} position={[6.593, 7.461, 8.876]} rotation={[0, -0.634, 0]} scale={2.706} />
      <mesh geometry={nodes.Cube002.geometry} material={nodes.Cube002.material} position={[10.484, 12.223, 11.739]} rotation={[0, -0.634, 0]} scale={2.706} />
      <mesh geometry={nodes.Cube003.geometry} material={nodes.Cube003.material} position={[6.567, 17.241, 8.857]} rotation={[0, -0.634, 0]} scale={2.706} />
      <group position={[3.637, 4.824, -7.566]} rotation={[1.814, -0.043, -1.564]} scale={5.474}>
        <mesh geometry={nodes.model.geometry} material={materials.mat14} />
        <mesh geometry={nodes.model_1.geometry} material={materials.mat18} />
        <mesh geometry={nodes.model_2.geometry} material={materials.mat23} />
        <mesh geometry={nodes.model_3.geometry} material={materials.mat21} />
      </group>
      <group position={[31.019, -0.207, -17.168]} rotation={[0, 0.211, 0]} scale={0.029}>
        <mesh geometry={nodes['10634_SpeedBoat_v01_LOD3001'].geometry} material={materials['_10634_SpeedBoat_v01_LOD310634_SpeedBoat_v01.001']} />
        <mesh geometry={nodes['10634_SpeedBoat_v01_LOD3001_1'].geometry} material={materials['glass.001']} />
      </group>
      <mesh geometry={nodes.Post001.geometry} material={materials.FencePost} position={[21.083, 4.552, 0.386]} rotation={[0, -0.93, 0]} scale={[0.501, 1.761, 0.501]} />
      <mesh geometry={nodes.Post002.geometry} material={materials.FencePost} position={[23.301, 5.209, 8.26]} rotation={[Math.PI, -1.34, Math.PI]} scale={[0.501, 1.761, 0.501]} />
      <mesh geometry={nodes.Post003.geometry} material={materials.FencePost} position={[15.083, 4.977, 20.309]} rotation={[Math.PI, -0.455, Math.PI]} scale={[0.501, 1.761, 0.501]} />
      <mesh geometry={nodes.Post004.geometry} material={materials.FencePost} position={[-2.479, 5.554, 22.027]} rotation={[-Math.PI, 0.087, -Math.PI]} scale={[0.501, 1.761, 0.501]} />
      <mesh geometry={nodes.Post005.geometry} material={materials.FencePost} position={[-11.757, 5.003, 19.753]} rotation={[-Math.PI, 0.601, -Math.PI]} scale={[0.595, 2.092, 0.595]} />
      <mesh geometry={nodes.Post006.geometry} material={materials.FencePost} position={[-14.835, 5.554, 10.31]} rotation={[-Math.PI, 1.231, -Math.PI]} scale={[0.501, 1.761, 0.501]} />
      <mesh geometry={nodes.Plane.geometry} material={nodes.Plane.material} position={[8.8, 3.555, -3.386]} rotation={[Math.PI / 2, 0, 0.106]} scale={[1, 1, 1.363]} />
      <mesh geometry={nodes.Post007.geometry} material={materials.FencePost} position={[-19.18, 5.554, 2.182]} rotation={[-Math.PI, 1.479, -Math.PI]} scale={[0.501, 1.761, 0.501]} />
      <mesh geometry={nodes.Post008.geometry} material={materials.FencePost} position={[-14.461, 5.554, -9.225]} rotation={[0, 1.047, 0]} scale={[0.501, 1.761, 0.501]} />
      <mesh geometry={nodes.Post009.geometry} material={materials.FencePost} position={[-8.261, 5.554, -18.273]} rotation={[0, 0.636, 0]} scale={[0.501, 1.761, 0.501]} />
      <mesh geometry={nodes.Post010.geometry} material={materials.FencePost} position={[0.437, 5.554, -21.096]} rotation={[0, 0.034, 0]} scale={[0.501, 1.761, 0.501]} />
      <mesh geometry={nodes.Post011.geometry} material={materials.FencePost} position={[6.959, 5.554, -20.177]} rotation={[0, -0.177, 0]} scale={[0.501, 1.761, 0.501]} />
      <mesh geometry={nodes.Plane001.geometry} material={materials.Water} position={[6.158, -0.503, 0]} />
    </group>
  )
}

useGLTF.preload('/models/credenz24/v1/v1.glb')
