version: '3.2'

services:
  backend:
    # restart: always
    ports:
      - "8000:8000"
    container_name: back
    command: gunicorn main_website.wsgi:application --bind 0.0.0.0:8000 --timeout 1800
    # command: python3 manage.py runserver
    build:
      context: ./server/
      dockerfile: Dockerfile
    volumes:
      - static_files:/user/src/app/staticfiles/
      - ./server/db.sqlite3:/user/src/app/db.sqlite3
  
    env_file:
      - ./server/.env

volumes:
  static_files: