/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 logo_new.glb
*/

import React, { useRef } from 'react'
import { useGLTF, useTexture } from '@react-three/drei'

export function JustLogoV3(props) {
  const { nodes, materials } = useGLTF('/models/justLogo/logov3.glb')
  const logoTexture = useTexture('/models/justLogo/logo.png')
  const baseTexture = useTexture('/models/justLogo/base.png')
  
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Base001.geometry} material={nodes.Base001.material} position={[0.05, 0.15, -4.27]} rotation={[Math.PI / 2, 0, 0]} scale={[1, 1, 1.04]} >
        <meshBasicMaterial map={baseTexture} map-flipY={false} />
      </mesh>
      <mesh geometry={nodes.Base002.geometry} material={nodes.Base002.material} position={[0.05, 0.15, -4.27]} rotation={[Math.PI / 2, 0, 0]} scale={[1, 1, 1.04]} >
      <meshBasicMaterial map={logoTexture} map-flipY={false} />
      </mesh>
    </group>
  )
}

useGLTF.preload('/models/justLogo/logov3.glb')
