/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 Logo_Base.glb
*/

import React, { useRef } from 'react'
import { useGLTF, useTexture } from '@react-three/drei'

export default function JustLogo(props) {
  const { nodes, materials } = useGLTF('/models/justLogo/logo.glb')
  
  const logoTexture = useTexture('/models/justLogo/logo.png')
  const baseTexture = useTexture('/models/justLogo/base.png')

  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Base.geometry} material={nodes.Base.material} position={[0.05, 0.15, -4.27]} rotation={[Math.PI / 2, 0, 0]} scale={[1, 1, 1.04]} >
        <meshBasicMaterial map={baseTexture} map-flipY={false} />
      </mesh>
      <mesh geometry={nodes.Plane006.geometry} material={nodes.Plane006.material} position={[-0.59, 0.47, -3.82]} rotation={[Math.PI / 2, -1.57, 0]} scale={[0.42, 2.98, 0.5]} >
        <meshBasicMaterial map={logoTexture} map-flipY={false} />
      </mesh>
    </group>
  )
}

useGLTF.preload('/models/justLogo/logo.glb')
