/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 .\\Model.glb
*/

import React, { useRef } from 'react'
import { Float, useGLTF, useTexture } from '@react-three/drei'

export default function LogoV6(props) {
  const { nodes, materials } = useGLTF('/models/v6/Model.glb')

  const logoTexture = useTexture('models/v6/textures/logo.png')
  const navTexture = useTexture('models/v6/textures/nav.png')
  const rocketTexture = useTexture('models/v6/textures/rocket.png')
  const sateliteTexture = useTexture('models/v6/textures/satelite.png')
  const spaceshipTexture = useTexture('models/v6/textures/spaceship.png')
  const tilesTexture = useTexture('models/v6/textures/tiles.png')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Wire.geometry} material={nodes.Wire.material} position={[-3.67, 0.23, 0.74]} rotation={[0, 0.97, 0]} >
        {/* <meshBasicMaterial map={bakedTexture} map-flipY={false} /> */}
      </mesh>
      <Float>
        <mesh geometry={nodes.Rocket_Ship_01.geometry} material={nodes.Rocket_Ship_01.material} position={[17.76, 23.14, -40.83]} rotation={[-0.44, 0.29, 1.18]} scale={0.1} >
          <meshBasicMaterial map={rocketTexture} map-flipY={false} />
        </mesh>
      </Float>
      
      <mesh geometry={nodes.Logo.geometry} material={nodes.Logo.material} position={[-0.12, 2.88, -4.16]} rotation={[Math.PI / 2, 0, 0]} scale={0.92} >
        <meshBasicMaterial map={logoTexture} map-flipY={false} />
      </mesh>
      <mesh geometry={nodes.Base.geometry} material={nodes.Base.material} position={[0.05, 0.13, -4.27]} rotation={[Math.PI / 2, 0, 0]} scale={[1, 1, 1.04]} >
        <meshBasicMaterial map={logoTexture} map-flipY={false} />
      </mesh>
      <mesh geometry={nodes.Terrain001.geometry} material={nodes.Terrain001.material} position={[-2.03, -0.05, 27.25]} rotation={[Math.PI / 2, 0, Math.PI]} >
        <meshBasicMaterial map={tilesTexture} map-flipY={false} />
      </mesh>
      <mesh geometry={nodes.Cylinder.geometry} material={nodes.Cylinder.material} position={[2.71, 0.98, 4.32]} rotation={[1.59, 0, 1.48]} scale={0.4} >
        <meshBasicMaterial map={sateliteTexture} map-flipY={false} />
      </mesh>
      <mesh geometry={nodes.Spaceship.geometry} material={nodes.Spaceship.material} position={[0.01, 1.2, 18.48]} rotation={[0.03, 0.61, -1.62]} scale={[0.14, 0.16, 0.14]} >
        <meshBasicMaterial map={spaceshipTexture} map-flipY={false} />
      </mesh>
      {/* <mesh geometry={nodes.NavStand.geometry} material={nodes.NavStand.material} position={[-2.78, -0.19, 6.73]} />
      <mesh geometry={nodes.Nav001.geometry} material={nodes.Nav001.material} position={[-2.51, 2.01, 6.96]} />
      <mesh geometry={nodes.Nav002.geometry} material={nodes.Nav002.material} position={[-2.51, 1.6, 6.96]} />
      <mesh geometry={nodes.Nav003.geometry} material={nodes.Nav003.material} position={[-2.51, 1.18, 6.96]} />
      <mesh geometry={nodes.Nav004.geometry} material={nodes.Nav004.material} position={[-2.51, 0.76, 6.96]} />
      <mesh geometry={nodes.Nav005.geometry} material={nodes.Nav005.material} position={[-2.51, 0.35, 6.96]} /> */}
    </group>
  )
}

useGLTF.preload('/models/v6/Model.glb')
