/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 .\\Logo_v4.glb
*/

import React, { useRef } from 'react'
import { useGLTF, useTexture, useBounds, Bounds, Float } from '@react-three/drei'
import { useFrame } from '@react-three/fiber'
import * as THREE from 'three'

export default function LogoV4(props) {
  const { nodes, materials } = useGLTF('/models/v4/Logo_v4.glb')
  const bakedTexture = useTexture('models/v4/texture.jpg')
  const skyTexture = useTexture('models/v4/sky.png')
  // bakedTexture.encoding = THREE.sRGBEncoding;


  return (
    <group {...props} dispose={null}>
      <group position={[0.05, 0.2, -4.21]}>
        <mesh geometry={nodes.Nav_6001.geometry} material={nodes.Nav_6001.material} rotation={[Math.PI / 2, 0, 0]} />
      </group>
      <mesh geometry={nodes['1'].geometry} material={nodes['1'].material} position={[0.05, 1.5, -37.88]} rotation={[Math.PI / 2, 0, 0]} > 
      <meshBasicMaterial map={skyTexture} map-flipY={false} />
      </mesh>
      <mesh geometry={nodes.Logo.geometry} material={nodes.Logo.material} position={[-0.3, 3.16, -3.01]} rotation={[Math.PI / 2, 0, 0]} >
      <meshBasicMaterial map={bakedTexture} map-flipY={false} />
      </mesh>
      <mesh geometry={nodes.Base.geometry} material={nodes.Base.material} position={[0.05, 0.13, -4.27]} rotation={[Math.PI / 2, 0, 0]} >
      <meshBasicMaterial map={bakedTexture} map-flipY={false} />
      </mesh>
      <mesh geometry={nodes.Terrain.geometry} material={nodes.Terrain.material} position={[0.05, 0.1, -4.61]} rotation={[Math.PI / 2, 0, 0]} >
      <meshBasicMaterial map={bakedTexture} map-flipY={false} />
      </mesh>
      <mesh geometry={nodes.plate.geometry} material={nodes.plate.material} position={[-2.96, 1.39, 6.94]} rotation={[Math.PI / 2, 0, 0]} >
      <meshBasicMaterial map={bakedTexture} map-flipY={false} />
      </mesh>
    </group>
  )
}

useGLTF.preload('/models/v4/Logo_v4.glb')
