/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 nth.glb --transform --simplify
*/

import React, { useRef } from 'react'
import { useGLTF, useTexture } from '@react-three/drei'

export default function Model1(props) {
  const { nodes, materials } = useGLTF('/models/explore/v1/explore-transformed.glb')
  const bgTexture = useTexture('models/explore/v1/textures/bg.png')
  const borderTexture = useTexture('models/explore/v1/textures/border.png')
  const screenTexture = useTexture('models/explore/v1/textures/screen.png')
  const wireTexture = useTexture('models/explore/v1/textures/wire.png')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Body_Cube041.geometry} material={materials.Basic} position={[0.33, 1.29, 0.62]} rotation={[Math.PI / 2, 0, 0]} scale={7} >
        <meshBasicMaterial map={borderTexture} map-flipY={false} />
      </mesh>
      <mesh geometry={nodes.Display_Slice007.geometry} material={materials.TD_Checker} position={[0.33, 1.29, 0.62]} rotation={[Math.PI / 2, 0, 0]} scale={7} >
        <meshBasicMaterial map={screenTexture} map-flipY={false} />
      </mesh>
      <mesh geometry={nodes.Plane001.geometry} material={materials.Material} position={[0.03, 7.29, -0.33]} rotation={[Math.PI / 2, 0, 0]} >
        <meshBasicMaterial map={bgTexture} map-flipY={false} />
      </mesh>
      <mesh geometry={nodes.BezierCurve.geometry} material={materials['Material.004']} position={[-8.32, -0.91, 0.33]} rotation={[Math.PI / 2, 0, 0]} >
        <meshBasicMaterial map={wireTexture} map-flipY={false} />
      </mesh>
      <mesh geometry={nodes.BezierCurve001.geometry} material={materials['Material.004']} position={[-8.32, -0.41, 0.33]} rotation={[Math.PI / 2, 0, 0]} >
        <meshBasicMaterial map={wireTexture} map-flipY={false} />
      </mesh>
    </group>
  )
}

useGLTF.preload('/models/explore/v1/explore-transformed.glb')
